### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by martingluckman** [vedicsociety/nobel-prize-data#20]
![image](https://user-images.githubusercontent.com/1072059/106672175-533fa580-65b8-11eb-8610-88563199f8ee.png)
![image](https://user-images.githubusercontent.com/1072059/106672195-5a66b380-65b8-11eb-8eb4-9a315be516e2.png)

![image](https://user-images.githubusercontent.com/1072059/106672216-62265800-65b8-11eb-8099-aa092483623d.png)

![image](https://user-images.githubusercontent.com/1072059/106672288-7ec29000-65b8-11eb-9aa0-500c855bd51e.png)

**Comment by maektwain** [comment]
I am currently running the development mode. So once we switch to build for production, it will be faster.

**Comment by martingluckman** [comment]
Tx
